### ISSUE TITLE
Create MD (markdown) file that explains the workflow

### ISSUE THREAD

**Issue by markband** [filetrust/k8-traffic-generator#11]
@markband commented on [Tue Aug 25 2020](https://github.com/filetrust/Open-Source/issues/3)

Create MD (markdown) file that explains the workflow above (i.e. capture this initial workflow to get up and running with the Glasswall SDK)for now this can be added to https://github.com/filetrust/k8-glasswall-rebuild

**Comment by faisaladnanpeltops** [comment]
See the workflow:

![image](https://user-images.githubusercontent.com/68223517/92043746-f62b9380-ed7c-11ea-8e09-dd4671865711.png)

**Comment by faisaladnanpeltops** [comment]
@ggrig , can you write a short diagram for above flow? This is useful for other engineers to understand how the Rebuild Engine is working. We must create a traffic generator for Rebuild Engine too.

**Comment by faisaladnanpeltops** [comment]
@ggrig , use the 5 seconds rule and estimate a number.
