### ISSUE TITLE
traffic generator golang version 

### ISSUE THREAD

**Issue by reem-masoud** [filetrust/k8-traffic-generator#17]

**Comment by Crispin-Courtenay** [comment]
Please list URL what traffic generator (multiple solutions).  And address why this vs. Google-native solution. It need not be an either-or scenario, could be A) & B).

**Comment by dinis-cruz-gw** [comment]
@Crispin-Courtenay what do you mean by "Google-native solution"?

**Comment by silvanayousry** [comment]
@Crispin-Courtenay can you please clarify what you mean ? 
we are working on the Golang version of traffic generator

**Comment by markband** [comment]
Hi @reem-masoud @silvanayousry can you provide an update on this issue? thanks!
