### ISSUE TITLE
Use file-drop.co.uk as the target system and check if the limit rate is 50 calls per seconds

### ISSUE THREAD

**Issue by faisaladnanpeltops** [filetrust/k8-traffic-generator#59]
DoD:
- Create a traffic generator that use the API in file-drop.co.uk to upload files. See screenshot.
- Check if the limit rate is 50 calls/files per second

![image](https://user-images.githubusercontent.com/68223517/92042967-85d04280-ed7b-11ea-8437-50689a479f66.png)

**Comment by faisaladnanpeltops** [comment]
@yardenshoham 
start with the 5 seconds rule and put a number.

**Comment by yardenshoham** [comment]
5 second rule estimation: 1

**Comment by yardenshoham** [comment]
Closed by #67 and #77
