### ISSUE TITLE
Create a demo video for PR #33

### ISSUE THREAD

**Issue by faisaladnanpeltops** [filetrust/k8-traffic-generator#65]

**Comment by xuxant** [comment]
I have created the video, @faisaladnanpeltops Sir, i will be sending the video to you in slack and please give me your review about it.

**Comment by faisaladnanpeltops** [comment]
Link to the video:
https://glasswallsolu-qbp1117.slack.com/files/U019M6PCFHD/F01AJ0N3XED/demo-traffic-to-minio.mp4
