### ISSUE TITLE
Provide a test suite that we can run in the target website, basically, give us a way to test the flow using the OVA.

### ISSUE THREAD

**Issue by faisaladnanpeltops** [filetrust/k8-traffic-generator#79]
Test Plan
1. Open https://www.gov.uk.glasswall-icap.com/
2. Open each root menu
3. Use search function with keywords: visa, immigration, benefit etc

See the credentials here:
https://glasswallsolu-qbp1117.slack.com/archives/C01A1KG0LC8/p1599604229435300

**Comment by NadHodeGW** [comment]
@faisaladnanpeltops 

Typical Test Scenario to use:

Open https://www.gov.uk.glasswall-icap.com/
Use search function with keywords: visa, immigration, benefit etc
Open each root menu & navigate down to files to download
Download files
Go to the file drop site -https://glasswall-file-drop.azurewebsites.net/
Process the downloaded files through file drop

Expected result: The file should be clean

**Comment by faisaladnanpeltops** [comment]
Rebuild API:
https://engineering.glasswallsolutions.com/docs/products/cloud-sdk/rebuild/rebuild-api

**Comment by faisaladnanpeltops** [comment]
https://forensic-workbench.com/
Username: admin
Pass: $Wall

**Comment by faisaladnanpeltops** [comment]
File-drop implementation:
https://github.com/filetrust/k8-traffic-generator/tree/master/upwork-devs/yarden-shoham/file-drop.co.uk

**Comment by pranaysahith** [comment]
From slack - 
* Create test result object* for each test step.
* The object is in JSON format. The object is shipped to ELK
